### PR TITLE
Update dependencies, update to Swift 4.2

### PR DESCRIPTION
**Pull request by weissazool**
There's one awkward thing right now with Stencil that will prevent this from building. Basically, since it's just a git submodule, there is no `Stencil` module to namespace or import, so the usage of `Stencil.normalize(value)` breaks.

Installing it via SPM or Carthage instead of git submodules should solve this issue. I'll probably add that as an additional commit within this PR but wanted to initially submit this as a heads up.

### CODE REVIEW

**Comment by weissazool** [comment]
Based on #3 it seems like the issue has already been raised.

**Comment by weissazool** [comment]
In trying to move Stencil to Carthage, some interfaces to the `Context` struct become unavailable. I don't understand the project well enough yet to work around it properly.

**Comment by njdehoog** [comment]
Hi @weissazool, thanks for the PR! I'm sorry to say this project is no longer maintained, so you're probably best off forking the project and starting from there.

Regarding your issue with Stencil. If I remember correctly, I created a fork of the main Stencil repo, because there were some bugs I needed to fix, or features added, for this project to work, and it was hard to get those changes applied in the main repo in the timeframe that I wanted. It could very well be that those bugs no longer exist or those features have been added in Stencil, which would make it possible to switch back. It might require some refactoring though.

**Comment by weissazool** [comment]
No problem - I figured this might not be maintained but thought I'd send the PR regardless. Appreciate the advice re: Stencil, cheers!

**Pull request closed without merging**
